version: '3.8'

services:
  jrub_database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: c_rub
    volumes:
      - ../volumes/postgresData:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
