version: '3.8'

services:
  jrub_migrator:
    build:
      context: ../backend
      dockerfile: Migrator.Dockerfile
    volumes:
      - ../volumes/backendConfigs/appsettings.migrator.json:/app/appsettings.json
    environment:
      ASPNETCORE_ENVIRONMENT: Production
